export const actionType = {
  GET_DETAIL_USER: "GET_DETAIL_USER",
  SET_USER_INFO: "SET_USER_INFO",
  SET_SIGN_IN: "SET_SIGN_IN",
  SET_SIGN_UP: "SET_SIGN_UP",
  GET_MAIN_CATEGORY: "GET_MAIN_CATEGORY",
  ADD_MAIN_CATEGORY: "ADD_MAIN_CATEGORY",
  GET_USER_LIST: "GET_USER_LIST",
  ADD_NEW_USER: "ADD_NEW_USER",
  EDIT_USER: "EDIT_USER",
  GET_SUB_CATEGORY: "GET_SUB_CATEGORY",
  GET_SERVICE_LIST: "GET_SERVICE_LIST",
};
